server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10


weixin:
  config:
    originalid: gh_c286e44246ca
    token: b8b6
    app_id: wx5c2005a3a8b211de
    app_secret: b6315d5f262488e39e4238371dc4846c
    template_id: AkfJYYs-ebQJZP3EGfBbtV1KAVak8HDhC5U5KZaJvHg

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

alipay:
  enabled: true
  app_id: 9021000141622405
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSNW7LKQzAMFVbaknbQSO0sSI5g07gcBbWHdHpmQkTjXSx95dy3+LQrElyQs89aP0h6Zs8RH5F4q0Yy9y1e/WYmT8FmGzhgynsd/1VM4uBYDU9j0MNEy/YrmoGlWPqVYXK/5Fmq9tJVcSaX8/zEjcfTkMaea3T4ARvTvzTXpRfCCbpVTtWqHlGzZFNwUSVGD9nS+5D1gQuUDQecDLZGOj/AKhh4xPvWl1UYetqd45CENgV6Rsq3F4AdpI5TsGILZxo+XVLs13p/XaN5yplfZSRSh+4t2VDeqgltsmFOV7PmXHxGXCS/ZBAZsopOA94WGeQ3tsg0i6DKfXUcsZRa0+VAgMBAAECggEAdBPl7XeevurgqZ4eGuuBbJCBKoYcVkXHa6DrKfms4hAZSL3YSISFb8SI3yU5oXi8F3N/In8CfXt0j84yYQeUOd3Y0hlswDHBVBMDVuSAamu2eTRHOJc2EmKOnMF4PPA/M6ZpiskAZR2p5CITV9jrWHhrABcAsckV3EUqpqldRIBgbCJ0ucfm0Ewk03ND7Ivnm89wARGXnXDJ5GPa5/HiJbnABmUSw1uPIgwblN7vbWby7DyV7WpHb0AD6eO0BpPGFFUNxv6uWS6LGpcNkuAT1In8Z1c77ykpYnsM4q4uaRe3avHWw6kQawmAxB1NouPtjCHs4Pge/LKBDPG3rnyQoQKBgQDXLhpruZv0dYDV4hudD7Q+9apoxU7RZY3frD3SeAJGnY8CS05nLWIaFQPx2FNfMq1OyhSuQOt7bO9ZsFboermBHUu9E3zlFL1ieihZlGin5MOS2E7PNdaP4XNfqipV1aekdPUnRMm4/PWI6LbE0gMBqcIYiztE9Wb/lYZZ4DM6rQKBgQCt8dbI/+gA5c/gwGpxiwerZ89jUQJJg97EQ+tNtVKDEh3xj//k0hOlUpvMXp62r+gaYqqlz3RuRre2hUyzed1vD3/pm5Up1LguwidjOxA3piKeFy+wMSs704fmbNtl0C1D2HeL5GpTfx/HPTzbycF/Eu3HD+tF+D7uW0oPigKtiQKBgQCHawA9o0W+huRZtj5ijauFo91mqiV8Kkkq5p7Rga0M+8MwUmw5Cpqeh3NAFEADvUTMPOje8QRBXMEU1KEdFX8A/orXpxgGoxK8ktwp4/gpERLzqyWNyfgJ/Hw7TD/wXNFv8hsGZ4f731Y2nx3Gp9Q0i70W7SiTsUzstBElJq+W0QKBgH5/yxEAMow8lTJBHOgYEOrRoxv6NOybz2zya/RmcmxJx6b+bz3MnWb0rcMx6MC5KtXNfYb6WRU9rqs5Q++eJ7B2GDMe55q1TYELx7M9p+ygkLph6Fd9WpC2pDWqYuAnRlP53+7HnZ+9arHt0g2RK3wrmurSo+qNv85+a1zjpFDpAoGAcPf4oUu0dFeSawG9Ipp7exydWwHViXwl+BX8vZFiWE3fg0rxzzxqmhBGBk3SKWbWSfptQ0fp2JtINY9HWzdwA4eBts1iSddUl2xtONJr1XQBlk6Sjk9lyyefhxngo4FuBMLRpgZDZMt/88XvPs6JQ3UooFW9rTJLzff+gLXhV1c=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhiUvThiZtAhNnU53jvA7+mc8N96x2CN8Bvd5eZPWtWETN7X9L6zClfmU216kFJG7ZVnAXLFnrx2lq/522GQMtPtDnzb2xjtTGcDQ5I5f1znGjFYpIUrMeQkdLe7MFK8y5nKDHgn91rsztotbtIsLr4Xvb5BI43BT0d9nFfpWsfsk8f2HDFHJa1lkpOdl28wsQIb++54tbDuS0ctPDURWspgdOG4MyECT9ZsUnEgNIq69DE0IX2fw3GwIUJJ31uKdZZ2C/eej/wWeo7/85EfZdqgaBF6mpxJSb3EU/9axbdVUTl+IG0jip8atpAZ6A41FVaWSIqpIJ6FyuVWG7j3iQQIDAQAB
  notify_url: http://zqiusu-studio.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do