# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose-2.4.yml up -d
version: '3.8'
# docker-compose -f docker-compose-app.yml up -d
# 你需要修改system为你自身系统的仓库名
services:
    # 部署前端项目
  nginx:
    image: nginx:1.25.1
    container_name: nginx
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl/
    networks:
      - my-network

  s-pay-mall:
    image: zqiusu/s-pay-mallapp:1.0
    container_name: s-pay-mall
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - TZ=PRC
      - SERVER_PORT=8080
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge